// Generated by gencpp from file gqcnn/GQCNNGraspPlannerSegmask.msg
// DO NOT EDIT!


#ifndef GQCNN_MESSAGE_GQCNNGRASPPLANNERSEGMASK_H
#define GQCNN_MESSAGE_GQCNNGRASPPLANNERSEGMASK_H

#include <ros/service_traits.h>


#include <gqcnn/GQCNNGraspPlannerSegmaskRequest.h>
#include <gqcnn/GQCNNGraspPlannerSegmaskResponse.h>


namespace gqcnn
{

struct GQCNNGraspPlannerSegmask
{

typedef GQCNNGraspPlannerSegmaskRequest Request;
typedef GQCNNGraspPlannerSegmaskResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GQCNNGraspPlannerSegmask
} // namespace gqcnn


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gqcnn::GQCNNGraspPlannerSegmask > {
  static const char* value()
  {
    return "b501d485b714517650cbb2c30c4f9ce3";
  }

  static const char* value(const ::gqcnn::GQCNNGraspPlannerSegmask&) { return value(); }
};

template<>
struct DataType< ::gqcnn::GQCNNGraspPlannerSegmask > {
  static const char* value()
  {
    return "gqcnn/GQCNNGraspPlannerSegmask";
  }

  static const char* value(const ::gqcnn::GQCNNGraspPlannerSegmask&) { return value(); }
};


// service_traits::MD5Sum< ::gqcnn::GQCNNGraspPlannerSegmaskRequest> should match
// service_traits::MD5Sum< ::gqcnn::GQCNNGraspPlannerSegmask >
template<>
struct MD5Sum< ::gqcnn::GQCNNGraspPlannerSegmaskRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gqcnn::GQCNNGraspPlannerSegmask >::value();
  }
  static const char* value(const ::gqcnn::GQCNNGraspPlannerSegmaskRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gqcnn::GQCNNGraspPlannerSegmaskRequest> should match
// service_traits::DataType< ::gqcnn::GQCNNGraspPlannerSegmask >
template<>
struct DataType< ::gqcnn::GQCNNGraspPlannerSegmaskRequest>
{
  static const char* value()
  {
    return DataType< ::gqcnn::GQCNNGraspPlannerSegmask >::value();
  }
  static const char* value(const ::gqcnn::GQCNNGraspPlannerSegmaskRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gqcnn::GQCNNGraspPlannerSegmaskResponse> should match
// service_traits::MD5Sum< ::gqcnn::GQCNNGraspPlannerSegmask >
template<>
struct MD5Sum< ::gqcnn::GQCNNGraspPlannerSegmaskResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gqcnn::GQCNNGraspPlannerSegmask >::value();
  }
  static const char* value(const ::gqcnn::GQCNNGraspPlannerSegmaskResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gqcnn::GQCNNGraspPlannerSegmaskResponse> should match
// service_traits::DataType< ::gqcnn::GQCNNGraspPlannerSegmask >
template<>
struct DataType< ::gqcnn::GQCNNGraspPlannerSegmaskResponse>
{
  static const char* value()
  {
    return DataType< ::gqcnn::GQCNNGraspPlannerSegmask >::value();
  }
  static const char* value(const ::gqcnn::GQCNNGraspPlannerSegmaskResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GQCNN_MESSAGE_GQCNNGRASPPLANNERSEGMASK_H
